language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t pungrumpy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pungrumpy/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-1'
  app: 'docker'
  env: 'Docker-env'
  bucket_name: $AWS_BUCKET_NAME
  bucket_path: 'docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
