name: Deploy frontend
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t pungrumpy/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true pungrumpy/docker-react npm test
